### ISSUE TITLE
rpm-py-installer fails to create rpm-python. 

### ISSUE THREAD

**Issue by davidbaril** [junaruga/rpm-py-installer#168] opened 2019-01-21 23:23 UTC
Environment:
CentOS 5.11 system, with miniconda2-4.3.21-Linux_x86_64 installed (Python 2.7.13)

FYI: miniconda2 version 4.3.21 was the last version of miniconda2 (Python 2.7.x) that supports CentOS 5.x.  Version 4.4 required CentOS 6.x or higher for the install script to work.

Output from the command follows.
RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer

The pip install of rpm-py-installer does generate the non-fatal error related to bdist_wheel and the "option -d not recognized".  This error is listed in the FAQ as being non-fatal and an artifact of Python2 environments.

[rpm-py-installer.out.txt](https://github.com/junaruga/rpm-py-installer/files/2780746/rpm-py-installer.out.txt)

Pip list shows no "rpm-python" package

$ pip list
Package          Version
---------------- -------
asn1crypto       0.22.0
cffi             1.10.0
conda            4.3.21
cryptography     1.8.1
enum34           1.1.6
idna             2.5
ipaddress        1.0.18
packaging        16.8
pip              18.1
pycosat          0.6.2
pycparser        2.17
pyOpenSSL        17.0.0
pyparsing        2.1.4
requests         2.14.2
rpm-py-installer 0.8.0
setuptools       27.2.0
six              1.10.0
wheel            0.29.0

**Comment by adammhaile** [comment] 2019-01-22 13:37
I'm also getting the same exact error when installing. Oddly it doesn't seem to effect the usage of the module that is installing this one (Koji) but it does make my installation scripts fail because technically the pip install failed.

**Comment by junaruga** [comment] 2019-01-22 15:37
@adammhaile thanks for the report.
I did not consider CentOS5.
Could you tell me about `rpm --version`, `python --version`?

**Comment by junaruga** [comment] 2019-01-22 15:39
The error is only CentOS5? How about other platform like CentOS6, Fedora, or Ubuntu?

**Comment by adammhaile** [comment] 2019-01-22 15:40
It's actually Fedora 28 in my case:
RPM version 4.14.2
Python 2.7.15

**Comment by adammhaile** [comment] 2019-01-22 15:41
@junaruga The original reporter (@davidbaril) was using Centos 5. In my personal case it's on Fedora

**Comment by junaruga** [comment] 2019-01-22 15:42
Sorry. now it is failed on f28 case.
https://travis-ci.org/junaruga/rpm-py-installer

**Comment by junaruga** [comment] 2019-01-22 15:55
It might work on Python 3.

**Comment by junaruga** [comment] 2019-01-22 15:55
I will debug for Python 2 case.

**Comment by adammhaile** [comment] 2019-01-22 15:56
Sadly I'm stuck at Py2... and for more info on the F28 case... it fails but doesn't emit a failure code if I just install a package that uses rpm-py-installer. But if I install a package that installs a package that uses this, it hard fails

**Comment by junaruga** [comment] 2019-01-22 15:57
How about after installing `rpm-devel`?
Can you do `dnf install rpm-devel` or `yum install rpm-devel`?

**Comment by junaruga** [comment] 2019-01-22 15:58
`rpm-py-installer` does something if `rpm-devel` is not installed.
It might be the logic has a problem.

**Comment by adammhaile** [comment] 2019-01-22 16:05
Nope:
```
  Running setup.py bdist_wheel for rpm-py-installer ... error
  Complete output from command /home/ahaile/.pyenv/rpm/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-YugMsC/rpm-py-installer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7O75zI --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option -d not recognized
  
  ----------------------------------------
  Failed building wheel for rpm-py-installer
```
Though, oddly, the return code is 0... but it still says the wheel failed to build

**Comment by junaruga** [comment] 2019-01-22 16:07
@davidbaril 

> RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer

Could you tell me `which pip` and `which python`?
Are you using virtualenv?

**Comment by junaruga** [comment] 2019-01-22 16:09
@adammhaile thanks for checking. Your report has same error message with @davidbaril .

**Comment by junaruga** [comment] 2019-01-22 17:24
Maybe I found the reason of the error on @davidbaril 's environment.

> Could you tell me which pip and which python?
> Are you using virtualenv?

From your report, maybe you are using

RPM: 4.4.2.3

When the RPM version is <= version 4.9.x that does not have `setup.py` to install by `pip` command in original RPM's source code, `rpm-py-installer` tries to install downloading existing RPM python binding package, copying it to your python's directory.

```
[INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.4.2.3-release.tar.gz'.
[DEBUG] CMD: yumdownloader rpm-python.x86_64
    [DEBUG] CMD: rpm2cpio ./rpm-python-4.4.2.3-36.el5_11.x86_64.rpm | cpio -idmv
    [DEBUG] CMD Return Code: [0], Stdout: [None], Stderr: [./usr/lib64/python2.4/site-packages/rpm
    ./usr/lib64/python2.4/site-packages/rpm/__init__.py
    ./usr/lib64/python2.4/site-packages/rpm/__init__.pyc
    ./usr/lib64/python2.4/site-packages/rpm/__init__.pyo
    ./usr/lib64/python2.4/site-packages/rpm/_rpmmodule.so
    264 blocks
    ]  
[DEBUG] Copy directory from 'usr/lib64/python2.4/site-packages/rpm' to '/home/dbaril/miniconda2/lib/python2.7/site-packages/rpm'
```

The problem is `rpm-python` RPM on CentOS5 is built by Python 2.4.
As copying the `rpm-python` binary built by Python 2.4 to Python 2.7 directory, the installed `rpm-python` is not recognized correctly.

The solution is 

1. 1st install your PRM Python binding RPM if you have not installed it yet.

```
# yum install rpm-python
```

2.1. Use system Python (`/usr/bin/python`) on your environment.
2.2. Or if you want to use your miniconda Python, you can create your environment like this.

```
$ virtualenv --system-site-packages --python=/path/to/your_miniconda_python ./venv2
```

On both 2.1 and 2.2, you do not have to install `rpm-py-installer`.
Sorry actually `rpm-py-installer` does not support CentOS5 right now.
And I have no idea how to run rpm-py-installer.

Maybe `wheel` error is not related to the issue.
Because `rpm-py-installer` intentionally skip `wheel` logic by the created error to disable `wheel`'s cache that prevents `rpm-py-installer` runs `install.py`.

**Comment by junaruga** [comment] 2019-01-22 17:39
@davidbaril are you setting `RPM_PY_INSTALL_BIN`=true ?

I found the this option is quite dangerous. 

```
$ echo $RPM_PY_INSTALL_BIN
```

Could you send me the log of `RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer`?

**Comment by davidbaril** [comment] 2019-01-22 19:34
The verbose pip install -vvv of rpm-py-installer was an attachment in the original posting.
I have NOT set any explicit RPM_PY* environment variables, unless the script sets them up.  echo $RPM_PY_INSTALL_BIN shows up blank.

Here is the Python information:
python --version
Python 2.7.13 :: Continuum Analytics, Inc.

This is miniconda2 Python 2.7.13.  It was installed from miniconda2-4.3.21-Linux-x86_64.sh which is the last miniconda2 version that will install under CentOS 5.x.

For pip:

 pip --version
pip 18.1 from /home/dbaril/miniconda2/lib/python2.7/site-packages/pip (python 2.7)

I do believe that you have identified one of the major issues, in that the system base python is version 2.4 (from CentOS 5.x), and I am trying to run under miniconda2 Python 2.7.13.  So trying to rebuild the setup.py for rpm-python will fail as you noted.  

The rpm-python package for CentOS 5.x (for Python 2.4) is installed. 

A second issue that may be happening ... is that miniconda2 Python allows the Python environment to be installed local to the user, and NOT require root privileged.  If the rpm-py-installer tries to do any writing in the "system" (Python 2.4) environment, it will be denied.


So what I have is a miniconda2 Python 2.7.13 environment that lacks any Python RPM bindings. No virtualenv is being used.  

I was hoping to use the rpm-py-installer to create the RPM bindings for this miniconda2 Python 2.7.13 installation.

**Comment by junaruga** [comment] 2019-01-22 21:05
@davidbaril 

> The verbose pip install -vvv of rpm-py-installer was an attachment in the original posting.
> I have NOT set any explicit RPM_PY* environment variables, unless the script sets them up. echo $RPM_PY_INSTALL_BIN shows up blank.

In you case, your RPM version on CentOS5 is 4.4.2.3.
If the RPM version is <= 4.9, the binary installation is executed without `RPM_PY_INSTALL_BIN` environment variable flag, as a default behavior.
Because in the version <= 4.9, can not build RPM Python binding from the source code by some technical reasons.

> So what I have is a miniconda2 Python 2.7.13 environment that lacks any Python RPM bindings. No virtualenv is being used.

Why do not you install and run virtualenv on your miniconda2 Python 2.7.13?

**Comment by junaruga** [comment] 2019-01-22 21:07
Sorry, this message "are you setting RPM_PY_INSTALL_BIN=true ?" was for @adammhaile not @davidbaril . Your guys's situation is different.

**Comment by junaruga** [comment] 2019-01-22 21:22
@davidbaril 
I found that perhaps this commit that is not released yet might fix your issue.
https://github.com/junaruga/rpm-py-installer/commit/e8e92463579a18f69a4227ab696aef8095d1b878

Can you try a `rpm-py-installer` new release 0.8.1 after it will be released?
I will release it today or tomorrow.

**Comment by adammhaile** [comment] 2019-01-23 12:32
Sadly still have the same issue with the new version on Fedora 28
```
  Complete output from command /home/ahaile/.pyenv/test2/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_0Z5pR/rpm-py-installer/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-myPFOh --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: option -d not recognized
  
  ----------------------------------------
  Failed building wheel for rpm-py-installer
```
It may be fine... because pip doesn't actually throw a fatal error. Just seems really odd.
Any particular diagnostics here I can give you?
Here's the verbose version https://gist.github.com/adammhaile/15b8b94fcddf9b6570b33f7871201265

**Comment by junaruga** [comment] 2019-01-23 16:09
@adammhaile Thanks for the log report.

> Any particular diagnostics here I can give you?
> Here's the verbose version https://gist.github.com/adammhaile/15b8b94fcddf9b6570b33f7871201265

Could you share the result of `pip list` after the `pip install -vvv koji`?
It seems `rpm-py-installer` is successfully done.
https://gist.github.com/adammhaile/15b8b94fcddf9b6570b33f7871201265#file-rpm_py_installer-log-L289

**Comment by davidbaril** [comment] 2019-01-23 16:35
Hi Jun,

I did try the new 0.8.1 release of rpm-py-installer as you suggested.  It still fails to create the rpm-python package, but it does create a "rpm" site package.  When you try to use the rpm bindings you now get a different error.  Details are posted later.

As to the question "Why do not you install and run virtualenv on your miniconda2 Python 2.7.13?"

I have never run virtualenv, and from what I understand ... it would not solve the problem, because it would need to also run under CentOS 5.x

Let me step back. 

My ultimate goal is to manage and upgrade (over time) legacy CentOS 5.x systems using Ansible.  We are trying to standardize on Ansible and it is working very well in the CentOS 6.x and 7.x environments.

Unfortunately, in a recent Ansible update, the requirements for a full-function managed target increase from Python 2.4 (which CentOS 5.x bundles) to Python 2.6+.  Thus, if you want full Ansible module functionality (and not just raw ssh-mode), the target needs to run Python 2.6+.  Ansible allows you to specify the path of the target's Python executable, so using a different Python version is straightforward.  CentOS 5.x EPEL provides Python 2.6 and Miniconda can easily provide Python 2.7.13 for CentOS 5.x

However, when you start actually using Ansible with non-system versions of Python you start getting errors about missing Python bindings for some function.  The Ansible "yum" module requires Python RPM bindings for the version of RPM installed on the target system.  Without the RPM bindings, you can't use the Ansible "yum" module, and you must use the "command" or "shell" function to run the equivalent yum command in the shell environment.  This can be done, but now you need to add the conditional capability to every Ansible yum module invocation to run properly on CentOS 5.x (or write a Ansible role passing it arguments, and have the role do the conditional execution).  Ansible also requires Python bindings for selinux to use the selinux-related Ansible modules.  In our case, we don't use the selinux Ansible modules often enough that adding the shell-based conditional alternative is reasonable,
 
So the ultimate goal is to be able to run the Ansible "yum" module (which requires Python RPM bindings) on a target CentOS 5.x system.  The other alternative is to back-rev Ansible to gain target Python 2.4 compatibility ... but you then loose functionality added in the newer versions of Ansible.

Here is a small 4-line Python test program that will use the Python rpm package to list the rpm packages.  This little test program needs to work correctly for Ansible to be able to run the Ansible "yum" module.

import rpm
ts = rpm.TransactionSet()
for h in ts.dbMatch():
    print h['name'], h['version'], h['release']

Every Ansible user who is facing the challenge of trying to manage and upgrade their old legacy CentOS 5.x systems would be very interested in getting python RPM bindings for a Python 2.6+ version that runs under CentOS 5.x.  The legacy older version of miniconda2 python 2.7.13 seemed like a better starting point than the CentOS 5.x EPEL Python 2.6 version.

rpm-py-installer seemed like a possible solution to generate the Python rpm bindings.

I will use a separate posting to detail the results of the new version 0.8.1 of rpm-py-installer.

**Comment by davidbaril** [comment] 2019-01-23 17:13
Here is the verbose log of installing rpm-py-installer 0.8.1
RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer
[rpm-installer.out.0.8.1.log3.txt](https://github.com/junaruga/rpm-py-installer/files/2788249/rpm-installer.out.0.8.1.log3.txt)

Here is the error you receive when running a small test program:
import rpm
ts = rpm.TransactionSet()
for h in ts.dbMatch():
print h['name'], h['version'], h['release']

 python testrpm.py
Traceback (most recent call last):
  File "testrpm.py", line 1, in <module>
    import rpm
  File "/home/dbaril/miniconda2/lib/python2.7/site-packages/rpm/__init__.py", line 7, in <module>
    from _rpm import *
ImportError: /home/dbaril/miniconda2/lib/python2.7/site-packages/rpm/_rpmmodule.so: undefined symbol: Py_InitModule4

The pip listing after the install.  There is NO rpm-python:
 pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package          Version
---------------- -------
asn1crypto       0.22.0
cffi             1.10.0
conda            4.3.21
cryptography     1.8.1
enum34           1.1.6
idna             2.5
ipaddress        1.0.18
packaging        16.8
pip              19.0.1
pycosat          0.6.2
pycparser        2.17
pyOpenSSL        17.0.0
pyparsing        2.1.4
requests         2.14.2
rpm-py-installer 0.8.1
setuptools       27.2.0
six              1.10.0
wheel            0.29.0

The Python rpm site package that was created by rpm-py-installer:
ls -l miniconda2/lib/python2.7/site-packages/rpm
total 148
-rw-r--r-- 1 dbaril dbaril    296 Dec  9  2014 __init__.py
-rw-r--r-- 1 dbaril dbaril    440 Jan 23 09:30 __init__.pyc
-rw-r--r-- 1 dbaril dbaril    430 Dec  9  2014 __init__.pyo
-rwxr-xr-x 1 dbaril dbaril 132656 Dec  9  2014 _rpmmodule.so

As you suspected these Python 2.7 rpm files seem to have been copied from the system's Python 2.4  site package rpm:

ls -l /usr/lib64/python2.4/site-packages/rpm
total 148
-rw-r--r-- 1 root root    296 Dec  9  2014 __init__.py
-rw-r--r-- 1 root root    430 Dec  9  2014 __init__.pyc
-rw-r--r-- 1 root root    430 Dec  9  2014 __init__.pyo
-rwxr-xr-x 1 root root 132656 Dec  9  2014 _rpmmodule.so

Note the 2014 creation dates and the same file sizes of the *.py and *.so files

If you google undefined symbol: Py_InitModule4 you get several hits.  They all seem to be related to Python 2.7 ... possibly missing the equivalence  Py_InitModule4 to Py_InitModule4_64

I have access to Python 2.6 via CentOS epel.  I will also try the new rpm-py-installer under Python 2.6.  It will take me time to setup the environment.

**Comment by davidbaril** [comment] 2019-02-05 00:39
I have given up trying to get the rpm-py-installer to work under CentOS 5.x

For my specific primary reason ... running Ansible, on a CentOS 5.x target, it was easier to create a VM without Ansible installed, and then manually install Ansible 2.3.4 from the RPM package using yum (to check dependencies).  Ansible 2.3.4 is the last version which supported CentOS 5.x (with bundled Python 2.4) properly, and used the CentOS 5.x Python 2.4 bindings for RPM, SELinux, and the other bindings that Ansible needs.

Ansible version 2.3.4 is missing the followon enhancements present in the current Ansible 2.7.5 version, but you still get the basic Ansible and Ansible module functionality ... enough to help you automate the migration to CentOS 6.x or newer.

Thank you for all your help.  The rpm-py-installer looks like a very useful package ... for CentOS 6 and newer.

Dave B

**Closed** 2019-02-05 00:39 UTC

**Comment by junaruga** [comment] 2019-02-05 16:57
@davidbaril Thanks for the report. Sorry I could not help you. I has been busy until 2 days ago.
I will carefully read your comments later, and I will try to support rpm-py-installer on CentOS5 in the future.
