### ISSUE TITLE
cannot "import rpm" in Xenial on Python 3 in Travis CI

### ISSUE THREAD

**Issue by ktdreyer** [junaruga/rpm-py-installer#194] opened 2019-06-14 22:06 UTC
I have "koji" listed as a dependency in my `setup.py`. I'm trying to test my project on Python 3.

When I use the following `.travis.yml` configuration for my project:

```yaml
dist: xenial
language: python
sudo: false
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - python setup.py develop
script:
  - py.test -v myproject/tests
addons:
  apt:
    packages:
    - rpm
    - librpm-dev
```

the build fails in Koji's "import rpm".
```
E   ModuleNotFoundError: No module named 'rpm'
```

The strange thing is that Travis appears to successfully install the rpm-py-installer package:

```
Searching for rpm-py-installer
Reading https://pypi.org/simple/rpm-py-installer/
Downloading https://files.pythonhosted.org/packages/57/f6/5042e10cbd6c4b6d0495a8339ef9f03747506d529498305c246073d02158/rpm-py-installer-0.9.0.tar.gz#sha256=5913def82cfef2244ad47656535f6db16bc9a05ee8a8aa1beb313b8a7522b267
Best match: rpm-py-installer 0.9.0
Processing rpm-py-installer-0.9.0.tar.gz
Writing /tmp/easy_install-_nlwtmrr/rpm-py-installer-0.9.0/setup.cfg
Running rpm-py-installer-0.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_nlwtmrr/rpm-py-installer-0.9.0/egg-dist-tmp-xwh2h946
[INFO] Installing...
[INFO] Created working directory '/tmp/tmpey1mppje-rpm-py-installer'
[INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.12.0.1-release.tar.gz'.
Package: libpopt-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 166
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: popt
Version: 1.16-10
Replaces: popt
Depends: libc6-dev | libc-dev, libpopt0 (= 1.16-10)
Conflicts: popt
Description: lib for parsing cmdline parameters - development files
 Popt was heavily influenced by the getopt() and getopt_long() functions,
 but it allows more powerful argument expansion. It can parse arbitrary
 argv[] style arrays and automatically set variables based on command
 line arguments. It also allows command line arguments to be aliased via
 configuration files and includes utility functions for parsing arbitrary
 strings into argv[] arrays using shell-like rules.
 .
 This package contains the popt static library and header file.
Original-Maintainer: Paul Martin <pm@debian.org>
Homepage: http://rpm5.org/
[INFO] Removed working directory '/tmp/tmpey1mppje-rpm-py-installer'
[INFO] Done successfully.
zip_safe flag not set; analyzing archive contents...
Moving rpm_py_installer-0.9.0-py3.6.egg to /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages
Adding rpm-py-installer 0.9.0 to easy-install.pth file
Installing install.py script to /home/travis/virtualenv/python3.6.7/bin
Installed /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/rpm_py_installer-0.9.0-py3.6.egg
```

**Comment by junaruga** [comment] 2019-06-15 00:10
Thanks for the report.

I try to reproduce it on 17th June Monday.

> Conflicts: popt

Conflicting?

**Comment by junaruga** [comment] 2019-06-15 00:35
@ktdreyer can you share your repository or can you create temporary branch enabling the Travis CI for the branch, with below code?

```
install:
  - RPM_PY_VERBOSE=true pip install -vvv rpm-py-installer
  - python setup.py develop
```

**Comment by junaruga** [comment] 2019-06-15 01:32
I noticed I could reproduce on a github repository referring your `.travis.yml` by myself.

**Comment by ktdreyer** [comment] 2019-06-18 23:16
My exact repository was https://travis-ci.org/red-hat-storage/bucko

Glad to hear you can reproduce it now.

**Comment by junaruga** [comment] 2019-06-20 20:46
Hi @ktdreyer now I tried to reproduce this issue using below code.

https://github.com/junaruga/rpm-py-installer-experiment-ubuntu-xenial
https://github.com/junaruga/rpm-py-installer-experiment-ubuntu-xenial/blob/master/.travis.yml

Interestingly it works now.
https://travis-ci.org/junaruga/rpm-py-installer-experiment-ubuntu-xenial/builds/548387789

```
$ pip list
Package          Version   
---------------- ----------
...
rpm-py-installer 0.9.0     
rpm-python       4.12.0.1  
...

$ python -c "import rpm; print(rpm.__version__)"
4.12.0.1
```

And the below log you showed about "libpopt-dev" is not appeared on my Travis CI's log.

```
...
[INFO] Downloading archive. 'https://github.com/rpm-software-management/rpm/archive/rpm-4.12.0.1-release.tar.gz'.
Package: libpopt-dev
Status: install ok installed
Priority: optional
Section: libdevel
...
```

Could you try on your environment now again? The issue still appears?

**Comment by junaruga** [comment] 2019-09-28 17:10
@ktdreyer I close this ticket as I could not reproduce it.
If you still face the error, please reopen it. Thanks.

**Closed by junaruga** 2019-09-28 17:10 UTC
